version: "3.9"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    env_file: ./.env
    environment: 
      - REACT_APP_CONTRACT

