name: Echidna Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Echidna
        uses: crytic/echidna-action@v2
        with:
          solc-version: 0.8.9
          files: contracts/test/fuzzing/CharityFuzz.sol
          contract: CharityFuzz
          config: contracts/test/fuzzing/echidnaConfig.yml
          crytic-args: --hardhat-ignore-compile --solc-remaps @openzeppelin/contracts=node_modules/@openzeppelin/contracts
        env:
          API_KEY: ${{ secrets.API_KEY }}
          COINMARKETCAP_API: ${{ secrets.COINMARKETCAP_API }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}