name: Slither Analysis
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Slither
        uses: crytic/slither-action@v0.2.0
        id: slither
        with:
          node-version: 16
          sarif: results.sarif
          fail-on: medium
        env:
          API_KEY: ${{ secrets.API_KEY }}
          COINMARKETCAP_API: ${{ secrets.COINMARKETCAP_API }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}